### ISSUE TITLE
Discuss multiple workflows and choose one standard workflow

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/git-workflow-teams#1]
The recommended workflow does not meet what I consider to be good practices for source code management on a small team.

In particular, the `rebase` advice should be discussed. I'm interested in hearing everyone's opinions!

**Comment by jrhorn424** [comment]
For my preferred workflow, the closest I can find on the net is [Github Flow](https://guides.github.com/introduction/flow/).

The workflow I like is basically:
- Use feature branches
- Merge features into master when done **using a PR** (no development branch)
- Update master regularly with `git pull --rebase` (no merge commits)
- Update features regularly (after previous step) with `git rebase master`
- Push once or twice a day
- If a branch is ever shared between two developers, don't rebase on that feature
- Optional: use rebase to squash and edit history before merging to master

Thus, merges are always meaningful and rebase is used to maintain sensible commit ordering.

**EDIT**: This is better:
- Use feature branches. Do not share feature branches.
- Do not work on `master`.
- Integrate features on `master` using a pull request through GitHub. The whole team does code review and merges until all conflicts are resolved.
- Everyone updates `master` after every merge with `git pull --rebase`.
- Everyone updates their features after every merge with `git rebase master`.
- Features are pushed once or twice a day (or more) with `git push --force`.
- No one ever types this: `git push master`.

**Comment by GA-MEB** [comment]
@jrhorn424 
The workflow recommended in the README is (with very minor alterations) the same one that was prescribed to the previous cohort. Why is that workflow not good practice? I ask because it impacts how I will write the step by step instructions for #5

**Comment by jrhorn424** [comment]
I wouldn't say it isn't **good**. I'd argue that it's too complex.

Small teams on small projects typically do not need `development` integration branches. What purpose does having an extra mainline branch serve?

I'd go so far as to say they need to see other workflows (they can do that by reading the tutorial we linked), but they need _absolute rules_ to follow.

I'm open to discussing those rules, the ones above are just a first pass using my own opinions.

**Comment by jrhorn424** [comment]
It should be noted also that I ended up teaching the workflow I outlined in this issue during the lesson, but that students followed the workflow from the lesson for the lab.

There was major confusion as to what "one central repository" meant. They thought that meant a GitHub org with forks and clones. Of course, it meant no forks, and orgs are unnecessary (but fine).

**Comment by jrhorn424** [comment]
Awesome work. Thanks @MattB-GA-Boston. :+1:
