### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/git-workflow-teams#16]
![rebase_01](https://cloud.githubusercontent.com/assets/3653013/13502525/5105d96e-e139-11e5-9db8-141694086e47.png)
![rebase_02](https://cloud.githubusercontent.com/assets/3653013/13502528/53566832-e139-11e5-94de-8c13a8345a01.png)
![rebase_03](https://cloud.githubusercontent.com/assets/3653013/13502529/552c4b4a-e139-11e5-969a-cfa525505311.png)
![rebase_04](https://cloud.githubusercontent.com/assets/3653013/13502533/57591394-e139-11e5-934b-709ff96add94.png)
![rebase_05](https://cloud.githubusercontent.com/assets/3653013/13502535/58f37500-e139-11e5-8f24-cc1bb783c5e9.png)
![rebase_06](https://cloud.githubusercontent.com/assets/3653013/13502539/5b41ef8a-e139-11e5-8641-d488f3b88f0e.png)

**Comment by jrhorn424** [comment]
Nice! Just so you know, you don't have to actually submit the issue to get the links to the CDN.

**Comment by GA-MEB** [comment]
Oh, ok. The tutorial wasn't explicit about it, so I figured I'd play it
safe and submit. Thanks for the info!

On Thu, Mar 3, 2016 at 2:41 PM, Jeffrey Horn notifications@github.com
wrote:

> Nice! Just so you know, you don't have to actually submit the issue to get
> the links to the CDN.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/git-workflow-teams/issues/16#issuecomment-191930440
> .

## 

_Matt Brendzel_
_Developer In Residence_
General Assembly - Boston | 51 Melcher Street, Boston, MA 02210
matt.brendzel@generalassemb.ly | @mattbrendzel | @GA_Boston | (215) 839 9428
http://generalassemb.ly

Join the party. Sign up for the GA newsletter
https://generalassemb.ly/locations/boston/.
