### ISSUE TITLE
git workflow

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/git-workflow-teams#18]
@gaand **Integrating a Feature** subsection within **The GA Group Project Workflow**, **step 2** was confusing. 

git pull --rebase

**Comment by gaand** [comment]
To me, "rebase" is semantically distinct from "pull" even though in the workflow presented they should be identical. 

I think it's worth reviewing and clarifying.

**Comment by BenGitsCode** [comment]
This was closed accidentally.
