### ISSUE TITLE
Erroneous instruction for Lab

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/git-workflow-teams#25]
Under the [Lab](https://github.com/ga-wdi-boston/git-workflow-teams#lab--using-the-ga-group-project-workflow) section:

> You may start by downloading the JS-Template as a ZIP and dropping those files into your repo. 

First of all, `JS-Template` is the wrong name. Secondly, this conflicts with the instructions on the Browser Template [README](https://github.com/ga-wdi-boston/browser-template/blob/master/README.md).

**Comment by BenGitsCode** [comment]
This is a duplicate of #24
