### ISSUE TITLE
Whatever demo/lab we use should have an explicit checklist, as per #5.

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/git-workflow-teams#6]
Each demo/lab should have an explicit checklist, as per #5.

**Comment by GA-MEB** [comment]
Don't know that I agree with this. Explaining but not demoing certain workflows is one way of resolving the tradeoff you mentioned in #3

**Comment by jrhorn424** [comment]
Awesome work. Thanks @MattB-GA-Boston. :+1:
